src/Entity/TypesOfWTO.php
<?php

namespace App\Entity;

use App\Repository\TypesOfWTORepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypesOfWTORepository::class)
 */
class TypesOfWTO
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typeWTO;

    /**
     * @ORM\OneToMany(targetEntity=AggregatesWTO::class, mappedBy="typesOfWTO", cascade={"remove"})
     */
    private $relation;

    /**
     * @ORM\OneToMany(targetEntity=WorkersSkillLevel::class, mappedBy="relation", cascade={"remove"})
     */
    private $workersSkillLevels;

    public function __construct()
    {
        $this->relation = new ArrayCollection();
        $this->workersSkillLevels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeWTO(): ?string
    {
        return $this->typeWTO;
    }

    public function setTypeWTO(string $typeWTO): self
    {
        $this->typeWTO = $typeWTO;

        return $this;
    }

    /**
     * @return Collection|AggregatesWTO[]
     */
    public function getRelation(): Collection
    {
        return $this->relation;
    }

    public function addRelation(AggregatesWTO $relation): self
    {
        if (!$this->relation->contains($relation)) {
            $this->relation[] = $relation;
            $relation->setTypesOfWTO($this);
        }

        return $this;
    }

    public function removeRelation(AggregatesWTO $relation): self
    {
        if ($this->relation->removeElement($relation)) {
            // set the owning side to null (unless already changed)
            if ($relation->getTypesOfWTO() === $this) {
                $relation->setTypesOfWTO(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string)$this->typeWTO;
    }

    /**
     * @return Collection|WorkersSkillLevel[]
     */
    public function getWorkersSkillLevels(): Collection
    {
        return $this->workersSkillLevels;
    }

    public function addWorkersSkillLevel(WorkersSkillLevel $workersSkillLevel): self
    {
        if (!$this->workersSkillLevels->contains($workersSkillLevel)) {
            $this->workersSkillLevels[] = $workersSkillLevel;
            $workersSkillLevel->setRelation($this);
        }

        return $this;
    }

    public function removeWorkersSkillLevel(WorkersSkillLevel $workersSkillLevel): self
    {
        if ($this->workersSkillLevels->removeElement($workersSkillLevel)) {
            // set the owning side to null (unless already changed)
            if ($workersSkillLevel->getRelation() === $this) {
                $workersSkillLevel->setRelation(null);
            }
        }

        return $this;
    }
}

src/Entity/WorkComplexityFactors.php
<?php

namespace App\Entity;

use App\Repository\WorkComplexityFactorsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkComplexityFactorsRepository::class)
 */
class WorkComplexityFactors
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $workComplexityFactor;

    /**
     * @ORM\ManyToOne(targetEntity=TypesOfEMAR::class, inversedBy="workComplexityFactors")
     */
    private $TypeOfEMAR;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWorkComplexityFactor(): ?string
    {
        return $this->workComplexityFactor;
    }

    public function setWorkComplexityFactor(string $workComplexityFactor): self
    {
        $this->workComplexityFactor = $workComplexityFactor;

        return $this;
    }



    public function __toString()
    {
        return $this->workComplexityFactor;
    }

    public function getTypeOfEMAR(): ?TypesOfEMAR
    {
        return $this->TypeOfEMAR;
    }

    public function setTypeOfEMAR(?TypesOfEMAR $TypeOfEMAR): self
    {
        $this->TypeOfEMAR = $TypeOfEMAR;

        return $this;
    }
}

src/Form/TypesOfWTOType.php
<?php

namespace App\Form;

use App\Entity\TypesOfWTO;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TypesOfWTOType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('typeWTO', TextType::class, [
                'label' => 'Вид ВТО']
                )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TypesOfWTO::class,
        ]);
    }
}

src/Controller/TypesOfWTOController.php
<?php

namespace App\Controller;

use App\Entity\TypesOfWTO;
use App\Form\TypesOfWTOType;
use App\Repository\TypesOfWTORepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class TypesOfWTOController extends AbstractController
{
    /**
     * @Route("/", name="types_of_wto_index", methods={"GET"})
     */
    public function index(TypesOfWTORepository $typesOfWTORepository): Response
    {
        return $this->render('types_of_wto/index.html.twig', [
            'types_of_wtos' => $typesOfWTORepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="types_of_wto_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $typesOfWTO = new TypesOfWTO();
        $form = $this->createForm(TypesOfWTOType::class, $typesOfWTO);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($typesOfWTO);
            $entityManager->flush();

            return $this->redirectToRoute('types_of_wto_index');
        }

        return $this->render('types_of_wto/new.html.twig', [
            'types_of_wto' => $typesOfWTO,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="types_of_wto_show", methods={"GET"})
     */
    public function show(TypesOfWTO $typesOfWTO): Response
    {
        return $this->render('types_of_wto/show.html.twig', [
            'types_of_wto' => $typesOfWTO,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="types_of_wto_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TypesOfWTO $typesOfWTO): Response
    {
        $form = $this->createForm(TypesOfWTOType::class, $typesOfWTO);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('types_of_wto_index');
        }

        return $this->render('types_of_wto/edit.html.twig', [
            'types_of_wto' => $typesOfWTO,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="types_of_wto_delete", methods={"POST"})
     */
    public function delete(Request $request, TypesOfWTO $typesOfWTO): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typesOfWTO->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($typesOfWTO);
            $entityManager->flush();
        }

        return $this->redirectToRoute('types_of_wto_index');
    }
}

templates/types_of_wto/_delete_form.html.twig
<form method="post" action="{{ path('types_of_wto_delete', {'id': types_of_wto.id}) }}" onsubmit="return confirm('Вы действительно хотите удалить этот элемент?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ types_of_wto.id) }}">
    <button class="btn btn-primary">Удалить</button>
</form>

templates/types_of_wto/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/types_of_wto/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Изменение видов ВТО{% endblock %}

{% block body %}
    <h1>Изменение видов ВТО</h1>

    {{ include('types_of_wto/_form.html.twig', {'button_label': 'Изменить'}) }}

    <a href="{{  path('types_of_wto_index') }}">Назад</a>
    {{ include('types_of_wto/_delete_form.html.twig') }}
{% endblock %}

templates/types_of_wto/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ВТО{% endblock %}

{% block body %}

	<div class="row">
		<a href="{{ path('maintenance_personnel_index') }}">Вторая таблица</a>
	</div>
	
	<h1>Высокотехнологическое оборудование</h1>

	<table class="table table-bordered" >
		<thead>
			<tr>
				<th><a href="{{ path('types_of_wto_new') }}">Тип ВТО</a></th>
				<th><a href="{{ path('aggregates_wto_new') }}">Аггрегаты ВТО</a></th>
				<th><a href="{{ path('types_of_emar_new') }}">Виды ТО и РО</a></th>
				<th><a href="{{ path('work_complexity_factors_new') }}">Коэффициенты сложности работ</a></th>
			</tr>
		</thead>
		<tbody>
			{% for types_of_wto in types_of_wtos %}
				<tr>
					<td><a href="{{ path('types_of_wto_edit', {'id': types_of_wto.id}) }}">{{ types_of_wto.typeWTO }}</a></td>
					<td>
						{% for AggregatesWTO in types_of_wto.getRelation() %}
							<p>
							<a href="{{ path('aggregates_wto_edit', {'id': AggregatesWTO.id}) }}">{{ AggregatesWTO.aggregateWTO }}</a>
							</p>
						{% endfor %}
					</td>
					<td>
						{% for AggregatesWTO in types_of_wto.getRelation() %}
							{% if (AggregatesWTO.getRelation().Count != 0) %}
								{{ AggregatesWTO.aggregateWTO }}
							{% endif %}
							{% for TypesOfEMAR in AggregatesWTO.getRelation() %}
								<p>
								<a href="{{ path('types_of_emar_edit', {'id': TypesOfEMAR.id}) }}">{{ TypesOfEMAR.typeOfEMAR }}</a>
								</p>
							{% endfor %}
						{% endfor %}
					</td>
					<td>
						{% for AggregatesWTO in types_of_wto.getRelation() %}
							{% for TypesOfEMAR in AggregatesWTO.getRelation() %}
								{% if (TypesOfEMAR.getWorkComplexityFactors().Count != 0) %}
								{{ TypesOfEMAR }}
								{% endif %}
								{% for WorkComplexityFactors in TypesOfEMAR.getWorkComplexityFactors() %}
									<p>
									<a href="{{ path('work_complexity_factors_edit', {'id':WorkComplexityFactors.id}) }}">{{ WorkComplexityFactors.workComplexityFactor }}</a>
									</p>
								{% endfor %}
							{% endfor %}
						{% endfor %}
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="3">Данных нет</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/types_of_wto/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Создание вида ВТо{% endblock %}

{% block body %}
    <h1>Создание видов ВТО</h1>

    {{ include('types_of_wto/_form.html.twig') }}

    <a href="{{ path('types_of_wto_index') }}">Назад</a>
{% endblock %}

templates/types_of_wto/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TypesOfWTO{% endblock %}

{% block body %}
    <h1>TypesOfWTO</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ types_of_wto.id }}</td>
            </tr>
            <tr>
                <th>TypeWTO</th>
                <td>{{ types_of_wto.typeWTO }}</td>
            </tr>
            <tr>
                <th>AggregateWTO</th>
                {% for AggregatesWTO in types_of_wto.getRelation() %}
                    <th>AggregatesWTO.aggregateWTO</th>
                {% endfor %}
            </tr>
        </tbody>
    </table>


    <a href="{{ path('types_of_wto_edit', {'id': types_of_wto.id}) }}">edit</a>

    {{ include('types_of_wto/_delete_form.html.twig') }}
{% endblock %}